### ISSUE TITLE
Errores del día 4

### ISSUE THREAD

**Issue by sgomez** [anthares101/todo#1]
Falta el return:

https://github.com/anthares101/todo/blob/54766c3c2642a6ccf88c571dbb52c775a569e267/src/Entity/User.php#L65

Es usename porque lo tenías mal puesto de primeras:
https://github.com/anthares101/todo/blob/54766c3c2642a6ccf88c571dbb52c775a569e267/src/Entity/User.php#L133
https://github.com/anthares101/todo/blob/54766c3c2642a6ccf88c571dbb52c775a569e267/src/Entity/User.php#L153

Aunque sería mejor pasarlo todo a username y crear un nuevo migration. Recuerda si lo dejas como username cambiarlo también en security.yaml

https://github.com/anthares101/todo/blob/54766c3c2642a6ccf88c571dbb52c775a569e267/config/packages/security.yaml#L11

**Comment by Anthares101** [comment]
En principio deberia estar corregido, dejo de momento el usename para evitar meter la pata en más cosas de la cuenta xd
